*** Variables ***
${health.radiobtn.gender}    //div[text()='replaceText ']
${health.pageheader.gender}    //div[@class="heading" and contains(text(),' Tell us about yourself, you are a.')]
${health.pageheader.whotoinsure}    //div[@class="heading" and contains(text(),'Who would you like to get insured')]
${health.radiobtn.option}    //input[@type='radio']/..//span[text()='replaceText']|//input[@type='radio']/../..//label[contains(.,'replaceText')]
${health.pageheader.areyouplanningto}    //p[@class="heading" and contains(text(),'Are you planning to have a child')]
${health.pageheader.whatisyourpincode}    //div[normalize-space()='What is your pincode?']
${health.text.pincode}    //div//input[@placeholder='Enter PIN, eg. 400001']
${health.pageheader.yourpreffered}    //p[@class='heading' and contains(text(),'Your preferred hospitals')]
${health.pageheader.whatisyourincomebracket}    //p[@class='heading' and contains(text(),'What is your income bracket')]
${health.radiobtn.income}    //input[@type='radio']/..//span[contains(text(),'replaceText')]
${health.pageheader.saveyourquote}    //p[@class='heading' and contains(text(),'Save your quotes now')]
${health.text.name}    //input[@placeholder='Name']
${health.text.email}    //input[@placeholder='Email']
${health.text.mobile}    //input[@placeholder='Mobile']
${health.pageheader.doesanyofthemembers}    //p[@class='heading'and contains(text(),'Does any of the members have any disease')]
