*** Variables ***
${health.radiobtn.gender}    //div[text()='replaceText ']
${health.pageheader.gender}    //div[@class="heading" and contains(text(),' Tell us about yourself, you are a.')]
${health.pageheader.whotoinsure}    //div[@class="heading" and contains(text(),'Who would you like to get insured')]
${health.radiobtn.option}    //input[@type='radio']/..//span[text()='replaceText']|//input[@type='radio']/../..//label[contains(.,'replaceText')]
${health.pageheader.areyouplanningto}    //p[@class="heading" and contains(text(),'Are you planning to have a child')]
${health.pageheader.whatisyourpincode}    //div[normalize-space()='What is your pincode?']
${health.text.pincode}    //input[@data-auto="pincode"]
${health.pageheader.yourpreffered}    //p[@class='heading' and contains(text(),'Your preferred hospitals')]
${health.pageheader.whatisyourincomebracket}    //p[@class='heading' and contains(text(),'What is your income bracket')]
${health.radiobtn.income}    //input[@type='radio']/..//span[contains(text(),'replaceText')]
${health.pageheader.saveyourquote}    //p[@class='heading' and contains(text(),'Save your quotes now')]
${health.text.name}    //input[@data-auto='leadName']
${health.text.email}    //input[@data-auto='leadEmail']
${health.text.mobile}    //input[@data-auto='leadMobile']
${health.pageheader.doesanyofthemembers}    //p[@class='heading'and contains(text(),'Does any of the members have any disease')]
${health.header.whenareyouplanningtohaveachild}    //p[@class='heading' and contains(text(),'When are you planning to have a child?')]
${health.radio.within1year}    //span[@class='ng-binding' and contains(text(),'Within 1 year')]
${health.radio.1-3years}    //span[@class='ng-binding' and contains(text(),'1-3 Years')]
${health.radio.morethan3years}    //span[@class='ng-binding' and contains(text(),'More than 3 Years')]
${health.radio.incomelessthan2.5}    //span[@class='ng-binding' and text()='Less than Rs 2.5 lakhs']
${health.radio.incomeupto5lakhs}    //span[@class='ng-binding' and text()='Rs 2.5 to 5 lakhs']
${health.radio.incomeupto10lakhs}    //span[@class='ng-binding' and text()='Rs 5 to 10 lakhs']
${health.radio.incomemorethan10lakhs}    //span[@class='ng-binding' and text()='More than Rs 10 lakhs']
